<a href="https://colab.research.google.com/github/mpoyatos/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [25]:
a = np.random.rand(5,5)
a

array([[0.55843415, 0.18604225, 0.68329945, 0.50437798, 0.7174221 ],
       [0.65951298, 0.99246809, 0.31777302, 0.04403612, 0.36899594],
       [0.15655699, 0.32054193, 0.06888029, 0.68453799, 0.23516968],
       [0.05396402, 0.05454231, 0.00707458, 0.89678652, 0.89609635],
       [0.95081622, 0.49836856, 0.68800812, 0.72102471, 0.18064888]])

In [22]:
a.shape

(5, 5)

In [26]:
b  = np.random.rand(5,5)
b

array([[0.49344224, 0.57769632, 0.61183145, 0.58239192, 0.44463316],
       [0.23312719, 0.34180889, 0.09729447, 0.84373205, 0.294866  ],
       [0.38435594, 0.35340005, 0.90561657, 0.18124183, 0.198975  ],
       [0.11889356, 0.19427134, 0.37955163, 0.81140316, 0.80450207],
       [0.0549344 , 0.42304454, 0.90225106, 0.46283027, 0.6358466 ]])

In [27]:
a + b

array([[1.0518764 , 0.76373858, 1.29513091, 1.0867699 , 1.16205526],
       [0.89264018, 1.33427699, 0.41506749, 0.88776817, 0.66386194],
       [0.54091293, 0.67394199, 0.97449686, 0.86577981, 0.43414468],
       [0.17285758, 0.24881365, 0.3866262 , 1.70818968, 1.70059842],
       [1.00575062, 0.9214131 , 1.59025918, 1.18385498, 0.81649547]])

In [28]:
a-b

array([[ 0.06499191, -0.39165407,  0.071468  , -0.07801394,  0.27278893],
       [ 0.42638579,  0.6506592 ,  0.22047855, -0.79969593,  0.07412994],
       [-0.22779894, -0.03285812, -0.83673627,  0.50329616,  0.03619469],
       [-0.06492953, -0.13972903, -0.37247705,  0.08538336,  0.09159428],
       [ 0.89588181,  0.07532402, -0.21424294,  0.25819444, -0.45519772]])

In [29]:
a*b

array([[0.275555  , 0.10747593, 0.4180641 , 0.29374566, 0.31898965],
       [0.15375041, 0.33923442, 0.03091756, 0.03715469, 0.10880436],
       [0.06017361, 0.11327954, 0.06237913, 0.12406691, 0.04679289],
       [0.00641597, 0.01059601, 0.00268517, 0.72765542, 0.72091137],
       [0.05223252, 0.2108321 , 0.62075606, 0.33371206, 0.11486497]])

In [30]:
a/b # Division elemento a elemento

array([[ 1.13171128,  0.32204161,  1.11680995,  0.86604564,  1.61351459],
       [ 2.82898348,  2.90357597,  3.2660953 ,  0.05219207,  1.25140212],
       [ 0.40732295,  0.90702288,  0.076059  ,  3.77693167,  1.1819057 ],
       [ 0.45388519,  0.28075325,  0.0186393 ,  1.10522927,  1.11385214],
       [17.30821034,  1.17805221,  0.7625462 ,  1.55785989,  0.28410764]])

In [31]:
np.transpose(a)

array([[0.55843415, 0.65951298, 0.15655699, 0.05396402, 0.95081622],
       [0.18604225, 0.99246809, 0.32054193, 0.05454231, 0.49836856],
       [0.68329945, 0.31777302, 0.06888029, 0.00707458, 0.68800812],
       [0.50437798, 0.04403612, 0.68453799, 0.89678652, 0.72102471],
       [0.7174221 , 0.36899594, 0.23516968, 0.89609635, 0.18064888]])

In [32]:
1/a # Matriz inversa

array([[  1.79072142,   5.37512299,   1.4634872 ,   1.98264007,
          1.39387957],
       [  1.51627038,   1.00758907,   3.14690025,  22.70863017,
          2.71005691],
       [  6.38745016,   3.11971662,  14.51794062,   1.4608393 ,
          4.25224881],
       [ 18.53086393,  18.3343904 , 141.35123471,   1.11509258,
          1.11595142],
       [  1.05172796,   2.00654713,   1.45347122,   1.38691501,
          5.53560047]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [33]:
import numpy as np

def suma_matrices(A, B):
  if len(A) != len(B) and len(A[1]) != len(B[1]):
    return None
  N = len(A)
  M = len(A[1])
  C = np.zeros((N, M))
  for i in range(0,N):
    for j in range(0,M):
      C[i,j] = A[i,j] + B[i,j]
  return C

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [36]:
import numpy as np

def transpuesta(A):
  N = len(A)
  M = len(A[1])
  C = np.zeros((M,N))
  for i in range(0,M):
    for j in range(0,N):
      C[i,j] = A[j,i]
  return C

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [49]:
R = np.array([[2, 0],[1, 2],[3,2]])
R

array([[2, 0],
       [1, 2],
       [3, 2]])

In [50]:
import numpy as np

def multiplicar_matrices(A, B):
  if len(A) != len(B[1]):
    return None
  N = len(A)
  M = len(A[1])
  C = np.zeros((N, M))
  for i in range(0,N):
    for j in range(0,M):
      s = 0
      for k in range(0,M):
        s = s + A[i,k] * B[k,j]
      C[i,j] = s
  return C

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))